# Generated by Django 3.2 on 2021-05-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210516_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
