# Generated by Django 3.2 on 2021-05-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210516_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='img',
        ),
    ]
