# Generated by Django 3.2 on 2021-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_registration_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
    ]
