# Generated by Django 3.2 on 2021-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_registration_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
