# Generated by Django 3.2 on 2021-05-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reg_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
