# Generated by Django 3.2 on 2021-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210517_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
    ]
