# Generated by Django 3.2 on 2021-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210517_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
