# Generated by Django 3.2 on 2021-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.ImageField(default='null', upload_to='pics'),
        ),
    ]
