# Generated by Django 3.2.3 on 2021-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
