# Generated by Django 3.2.3 on 2021-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
