# Generated by Django 3.2.3 on 2021-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_reg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('start_price', models.CharField(default='null', max_length=50)),
                ('end_price', models.CharField(default='null', max_length=50)),
                ('millage', models.CharField(default='null', max_length=50)),
                ('cc', models.CharField(default='null', max_length=50)),
                ('type', models.CharField(default='null', max_length=50)),
                ('image', models.ImageField(default='null', upload_to='pics')),
            ],
        ),
    ]
