# Generated by Django 3.2.3 on 2021-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='null', max_length=50)),
                ('lname', models.CharField(default='null', max_length=50)),
                ('licence', models.CharField(default='null', max_length=50)),
                ('pickdate', models.CharField(default='null', max_length=50)),
                ('dropdate', models.CharField(default='null', max_length=50)),
                ('location', models.CharField(default='null', max_length=100)),
                ('image', models.ImageField(default='null', upload_to='pics')),
            ],
        ),
    ]
