# Generated by Django 3.2.3 on 2021-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_carbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbook',
            name='status',
            field=models.CharField(default='cancled', max_length=100),
        ),
    ]
