# Generated by Django 3.2.3 on 2021-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_carbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbook',
            name='username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
