# Generated by Django 3.2.3 on 2021-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_carbook_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbook',
            name='carname',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
