# Generated by Django 3.2.3 on 2021-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(default='null', max_length=50)),
                ('cardnumber', models.CharField(default='null', max_length=50)),
                ('carddate', models.CharField(default='null', max_length=50)),
                ('cardcvv', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='end_price',
            field=models.IntegerField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='start_price',
            field=models.IntegerField(default='null', max_length=50),
        ),
    ]
